### ISSUE TITLE
Use state plane projections for state shapes?

### ISSUE THREAD

**Issue by TylerFisher** [The-Politico/politico-civic-geography#5]
see: https://github.com/veltman/d3-stateplane
https://en.wikipedia.org/wiki/State_Plane_Coordinate_System

**Comment by hobbes7878** [comment]
Right now we keep all geometries in decimal degrees so we can mix and match. Making this change would mean either creating a division level that isn't interoperable with child geometries or making the conversion down the entire geometry chain.

I get that the coordinate system is marginally better display but ... is that really worth it?

**Comment by hobbes7878** [comment]
Here's my biggest worry about interoperabiltiy:

> the system is highly accurate within each zone (error less than 1:10,000). Outside a specific state plane zone accuracy rapidly declines, thus the system is not useful for regional or national mapping.

**Comment by TylerFisher** [comment]
Good point, national maps wouldn't work out.

**Comment by hobbes7878** [comment]
Closing this out per discussion.
